apiVersion: batch/v1
kind: Job
metadata:
  name: batch-app
spec:
  backoffLimit: 4
  completions: 8
  parallelism: 2
  template:
    spec:
      containers:
      - name: job
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args: ["echo running job from $HOSTNAME!"]
      restartPolicy: Never