apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-nginx
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app_name: sts-nginx
  serviceName: nginx-sts
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      labels:
        app_name: sts-nginx
        app.kubernetes.io/version: "1.0"
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: html
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 100M